hpc <- read.table(file = 'household_power_consumption.txt', sep = ";", stringsAsFactors = FALSE, header = TRUE)
#install.packages("lubridate")
#install.packages("dplyr")
library(lubridate)
library(dplyr)
hpc$DateTime <- paste(hpc$Date, hpc$Time)
hpc$Date <- dmy(hpc$Date)
hpc_set <- hpc %>% filter(Date == '2007-02-01' | Date == "2007-02-02")
hpc_set$DateTime <- dmy_hms(hpc_set$DateTime)
hpc_set$Sub_metering_1 <- as.numeric(hpc_set$Sub_metering_1)
hpc_set$Sub_metering_2 <- as.numeric(hpc_set$Sub_metering_2)
hpc_set$Sub_metering_3 <- as.numeric(hpc_set$Sub_metering_3)
png(file = "plot2.png")
with(hpc_set, plot(DateTime, Global_active_power, ylab = "Global Active Power (kilowatts)", xlab = "", type = "l"))
dev.off()
