png(file = "plot4.png")
par(mfrow = c(2,2))
with(hpc_set, plot(DateTime, Global_active_power, ylab = "Global Active Power", xlab = "", type = "l"))
with(hpc_set, plot(DateTime, Voltage, ylab = "Voltage", xlab = "datetime", type = "l"))
plot(hpc_set$DateTime, hpc_set$Sub_metering_1, type = "n", xlab = "", ylab = "Energy sub metering")
points(hpc_set$DateTime, hpc_set$Sub_metering_1, type = "l")
points(hpc_set$DateTime, hpc_set$Sub_metering_2, type = "l", col = "red")
points(hpc_set$DateTime, hpc_set$Sub_metering_3, type = "l", col = "blue")
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
with(hpc_set, plot(DateTime, Global_reactive_power, xlab = "datetime", type = "l"))
dev.off()
