hpc <- read.table(file = 'household_power_consumption.txt', sep = ";", stringsAsFactors = FALSE, header = TRUE)
#install.packages("lubridate")
#install.packages("dplyr")
library(lubridate)
library(dplyr)
hpc$DateTime <- paste(hpc$Date, hpc$Time)
hpc$Date <- dmy(hpc$Date)
hpc_set <- hpc %>% filter(Date == '2007-02-01' | Date == "2007-02-02")
hpc_set$Sub_metering_1 <- as.numeric(hpc_set$Sub_metering_1)
hpc_set$Sub_metering_2 <- as.numeric(hpc_set$Sub_metering_2)
hpc_set$Sub_metering_3 <- as.numeric(hpc_set$Sub_metering_3)
png(file = "plot3.png")
plot(hpc_set$DateTime, hpc_set$Sub_metering_1, type = "n", xlab = "", ylab = "Energy sub metering")
points(hpc_set$DateTime, hpc_set$Sub_metering_1, type = "l")
points(hpc_set$DateTime, hpc_set$Sub_metering_2, type = "l", col = "red")
points(hpc_set$DateTime, hpc_set$Sub_metering_3, type = "l", col = "blue")
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()
