png(file = "plot3.png")
plot(hpc_set$DateTime, hpc_set$Sub_metering_1, type = "n", xlab = "", ylab = "Energy sub metering")
points(hpc_set$DateTime, hpc_set$Sub_metering_1, type = "l")
points(hpc_set$DateTime, hpc_set$Sub_metering_2, type = "l", col = "red")
points(hpc_set$DateTime, hpc_set$Sub_metering_3, type = "l", col = "blue")
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()
